### ISSUE TITLE
Tests are failing when run with Django 1.6

### ISSUE THREAD

**Issue by gregmuellegger** [pydanny/django-admin2#387]
As discovered by @tyrion in #386 and #384, some tests fail currently in the develop branch. But this only happens if you are using Django 1.6. Here is a log for the failing tests:

    Creating test database for alias 'default'...
    E..................................................................F..FF..............E...................................................................................................
    ======================================================================
    ERROR: test_admin_binding (blog.tests.test_permissions.TemplatePermissionTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "example/blog/tests/test_permissions.py", line 93, in test_admin_binding
        post_admin = djadmin2.default.get_admin_by_name('blog_post')
      File "/home/gregor/projects/django-admin2/djadmin2/core.py", line 138, in get_admin_by_name
        u'No object admin found with name {}'.format(repr(name)))
    ValueError: No object admin found with name 'blog_post'

    ======================================================================
    ERROR: test_multi_widget (blog.tests.test_modelforms.GetFloppyformWidgetTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "example/blog/tests/test_modelforms.py", line 295, in test_multi_widget
        floppyforms.widgets.MultiWidget)
      File "example/blog/tests/test_modelforms.py", line 21, in assertExpectWidget
        new_instance = floppify_widget(instance)
      File "/home/gregor/projects/django-admin2/djadmin2/forms.py", line 213, in floppify_widget
        return create_widget(widget)
      File "/home/gregor/projects/django-admin2/djadmin2/forms.py", line 46, in create_new_widget
        copy_attributes)
      File "/home/gregor/projects/django-admin2/djadmin2/forms.py", line 30, in _copy_attributes
        setattr(new_widget, attr, original_value)
    AttributeError: can't set attribute

    ======================================================================
    FAIL: test_decimal_field (blog.tests.test_modelforms.FieldWidgetTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "example/blog/tests/test_modelforms.py", line 446, in test_decimal_field
        self.assertTrue(isinstance(widget, floppyforms.widgets.NumberInput))
    AssertionError: False is not true

    ======================================================================
    FAIL: test_float_field (blog.tests.test_modelforms.FieldWidgetTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "example/blog/tests/test_modelforms.py", line 437, in test_float_field
        self.assertTrue(isinstance(widget, floppyforms.widgets.NumberInput))
    AssertionError: False is not true

    ======================================================================
    FAIL: test_integer_field (blog.tests.test_modelforms.FieldWidgetTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "example/blog/tests/test_modelforms.py", line 455, in test_integer_field
        self.assertTrue(isinstance(widget, floppyforms.widgets.NumberInput))
    AssertionError: False is not true

    ----------------------------------------------------------------------
    Ran 186 tests in 9.679s

    FAILED (failures=3, errors=2)
    Destroying test database for alias 'default'...

I will try to tackle this till the weekend.

**Comment by andrewsmedina** [comment]
closed by #403.
