### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by nickbewley** [pydanny/django-admin2#412]
Is this just me? Fresh install `pip install django-admin2` on Django 1.7.1 (mod_wsgi 3.5/Python 3.4)

```
Downloading/unpacking django-admin2
  Downloading django-admin2-0.6.1.tar.gz (129kB): 129kB downloaded
  Running setup.py (path:/tmp/pip_build_nbewley/django-admin2/setup.py) egg_info for package django-admin2

Requirement already satisfied (use --upgrade to upgrade): django>=1.5.0 in /home/nbewley/webapps/guerrilla/lib/python3.4/Django-1.7.1-py3.4.egg (from django-admin2)
Downloading/unpacking django-braces>=1.0.0 (from django-admin2)
  Downloading django_braces-1.4.0-py2.py3-none-any.whl
Downloading/unpacking django-extra-views>=0.6.2 (from django-admin2)
  Downloading django_extra_views-0.6.5-py2.py3-none-any.whl
Downloading/unpacking djangorestframework>=2.3.3 (from django-admin2)
  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):   1%  4.1k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):   2%  8.2k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):   4%  12kB  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  33%  102k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  34%  106k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  36%  110k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  37%  114k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  38%  118k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  40%  122k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  41%  126k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  42%  131k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  44%  135k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  45%  139k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  46%  143k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  48%  147k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  49%  151k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  50%  155k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  52%  159k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  53%  163k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  54%  167k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  56%  172k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  57%  176k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  58%  180k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  60%  184k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  61%  188k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  62%  192k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  64%  196k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  65%  200k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  66%  204k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  68%  208k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  69%  212k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  71%  217k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  72%  221k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  73%  225k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  75%  229k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  76%  233k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  77%  237k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  79%  241k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  80%  245k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  81%  249k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  83%  253k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  84%  258k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  85%  262k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  87%  266k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  88%  270k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  89%  274k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  91%  278k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  92%  282k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  93%  286k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  95%  290k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  96%  294k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  97%  299k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):  99%  303k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB): 100%  305k  Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB):             Downloading djangorestframework-3.0.3-py2.py3-none-any.whl (305kB): 305kB downloaded
Downloading/unpacking django-floppyforms>=1.1 (from django-admin2)
  Downloading django-floppyforms-1.3.0.tar.gz (2.2MB): 2.2MB downloaded
  Running setup.py (path:/tmp/pip_build_nbewley/django-floppyforms/setup.py) egg_info for package django-floppyforms

    warning: no files found matching '*.html' under directory 'floppyforms/tests/templates'
Downloading/unpacking django-filter>=0.6 (from django-admin2)
  Downloading django_filter-0.9.1-py2.py3-none-any.whl
Downloading/unpacking django-crispy-forms>=1.3.2 (from django-admin2)
  Downloading django-crispy-forms-1.4.0.tar.gz (47kB): 47kB downloaded
  Running setup.py (path:/tmp/pip_build_nbewley/django-crispy-forms/setup.py) egg_info for package django-crispy-forms

    warning: no files found matching '*' under directory 'crispy_forms/static'
Downloading/unpacking six (from django-braces>=1.0.0->django-admin2)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: django-admin2, django-braces, django-extra-views, djangorestframework, django-floppyforms, django-filter, django-crispy-forms, six
  Running setup.py install for django-admin2

      File "/home/nbewley/lib/python3.4/djadmin2/tests/test_renderers.py", line 60
        out = self.renderer(dt.time(13, 37, 01), None)
                                             ^
    SyntaxError: invalid token

      File "/home/nbewley/lib/python3.4/djadmin2/types.py", line 227
        raise new_exception, None, trace
                           ^
    SyntaxError: invalid syntax

Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/local/lib/python3.4/site-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pip/req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/local/lib/python3.4/site-packages/pip/req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/local/lib/python3.4/site-packages/pip/wheel.py", line 215, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.4/site-packages/pip/wheel.py", line 205, in clobber
    os.makedirs(destdir)
  File "/usr/local/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/site-packages/django_braces-1.4.0.dist-info'

Storing debug log for failure in /home/nbewley/.pip/pip.log
```

Thanks for any ideas or suggestions.

**Comment by pydanny** [comment]
The current release of django-admin2 does not work with Django 1.7. Master here on GitHub does work, but as it's not yet finalized, your success with it may vary. There will probably be a formal release soon.

**Comment by nickbewley** [comment]
Awesome. Thanks!

As a designer, I am very excited about this project.

**Comment by galuszkak** [comment]
@nickbewley could you help for example with this #360 ? :)

**Comment by nickbewley** [comment]
@galuszkak I will do my best. I will most likely create a custom theme. If I end up working with bootstrap, though, I will do my best to address that!
